### ISSUE TITLE
How can I get your dataset 'GitHubRenames'?

### ISSUE THREAD

**Issue by zoubaihan** [squaresLab/VarCLR#1]
As the title, I want train my own model based on the dataset 'GitHubRenames' you proposed in the paper. How can I get your dataset 'GitHubRenames'?

**Comment by qibinc** [comment]
We have sent the dataset in an email to @zoubaihan . Since the asker didn't reply, we mark this issue as resolved. For others who want this dataset, please stay tuned while we work on releasing the data and pre-training code!

**Comment by zoubaihan** [comment]
Oh, I have received your email. Thank you very much!
