### ISSUE TITLE
Call `encode()` with GPU

### ISSUE THREAD

**Issue by vcwai** [squaresLab/VarCLR#2]
It would be great if there is an option to call `model.encode("squareslab")` with GPU instead of CPU.

If we call `model.to(torch.device("cuda"))`, it doesn't work because `return_dict` is on CPU:
https://github.com/squaresLab/VarCLR/blob/2fe9595c2c056310e7de376b61d61ecb683f8160/varclr/models/encoders.py#L121

**Comment by qibinc** [comment]
Hi @victorcwai ,

You can add

```python
return_dict = dict(
    input_ids=return_dict["input_ids"].to("cuda")
    attention_mask=return_dict["attention_mask"].to("cuda")
)
```

**Comment by vcwai** [comment]
Yes thank you. 
But in my opinion, it would also be great if we are able to choose whether to use CPU and GPU in the `encode()` API. :-)
